### ISSUE TITLE
Mine and Blade crash on arrow pick up

### ISSUE THREAD

**Issue by Goujer** [Legojer/LittleMaidMobEnhanced#4]
---- Minecraft Crash Report ----
// There are four lights!

Time: 8/3/16 9:20 AM
Description: Ticking entity

java.lang.ClassCastException: littleMaidMobX.inventory.InventoryLittleMaid cannot be cast to mods.battlegear2.api.core.InventoryPlayerBattle
at mods.battlegear2.items.arrows.AbstractMBArrow.tryPickArrow(AbstractMBArrow.java:87)
at mods.battlegear2.items.arrows.AbstractMBArrow.func_70100_b_(AbstractMBArrow.java:67)
at littleMaidMobX.entity.EntityLittleMaid.func_70636_d(EntityLittleMaid.java:1790)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:272)
at littleMaidMobX.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:1989)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)
at WorldServerOF.func_72870_g(WorldServerOF.java:347)
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at mods.battlegear2.items.arrows.AbstractMBArrow.tryPickArrow(AbstractMBArrow.java:87)
at mods.battlegear2.items.arrows.AbstractMBArrow.func_70100_b_(AbstractMBArrow.java:67)
at littleMaidMobX.entity.EntityLittleMaid.func_70636_d(EntityLittleMaid.java:1790)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:272)
at littleMaidMobX.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:1989)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)
at WorldServerOF.func_72870_g(WorldServerOF.java:347)
at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Entity being ticked --
Details:
Entity Type: lmmx.LittleMaid (littleMaidMobX.entity.EntityLittleMaid)
Entity ID: 286473
Entity Name: entity.lmmx.LittleMaid.name
Entity's Exact location: -168.12, 93.00, 299.94
Entity's Block location: World: (-169,93,299), Chunk: (at 7,5,11 in -11,18; contains blocks -176,0,288 to -161,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Entity's Momentum: -0.05, -0.08, -0.09
Stacktrace:
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
Level name: New World
All players: 1 total; [EntityPlayerMP['Mariku_Junrei'/111353, l='New World', x=-169.23, y=93.00, z=297.63]]
Chunk stats: ServerChunkCache: 514 Drop: 0
Level seed: -229126503491401923
Level generator: ID 00 - default, ver 1. Features enabled: true
Level generator options:
Level spawn location: World: (-50,64,248), Chunk: (at 14,4,8 in -4,15; contains blocks -64,0,240 to -49,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Level time: 6181 game time, 6181 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 147327 (now: false), thunder time: 68266 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 3552085912 bytes (3387 MB) / 5154013184 bytes (4915 MB) up to 5154013184 bytes (4915 MB)
JVM Flags: 30 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -Xms5G -Xmn2G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=500 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -XX:UseSSE=3 -XX:+UseLargePages -XX:+UseBiasedLocking -Xincgc
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 65, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 64 mods loaded, 64 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAAAAAAA mcp{9.05} [Minecraft Coder Pack](minecraft.jar)
UCHIJAAAAAAAAA FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar)
UCHIJAAAAAAAAA Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar)
UCHIJAAAAAAAAA Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar)
UCHIJAAAAAAAAA CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar)
UCHIJAAAAAAAAA OldModelLoader{1.4.4} [LMMNX OldModelLoader](minecraft.jar)
UCHIJAAAAAAAAA NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar)
UCHIJAAAAAAAAA backpacks16840{3.1.0} [Backpacks!](zz-backpacks 1.7.10 - 3.1.0.jar)
UCHIJAAAAAAAAA <CoFH ASM>{000} [CoFH ASM](minecraft.jar)
UCHIJAAAAAAAAA mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar)
UCHIJAAAAAAAAA FastCraft{1.23} [FastCraft](fastcraft-1.23.jar)
UCHIJAAAAAAAAA gilded-games-util{1.7.10-1.2} [Gilded Games Utility](gilded-games-util-1.7.10-1.9.jar)
UCHIJAAAAAAAAA battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar)
UCHIJAAAAAAAAA bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar)
UCHIJAAAAAAAAA Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar)
UCHIJAAAAAAAAA abyssalcraft{1.9.1.2} [AbyssalCraft](AbyssalCraft-1.7.10-1.9.1.2-FINAL.jar)
UCHIJAAAAAAAAA Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar)
UCHIJAAAAAAAAA Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar)
UCHIJAAAAAAAAA acintegration{1.4.5} [AbyssalCraft Integration](AbyssalCraft Integration-1.7.10-1.4.5.jar)
UCHIJAAAAAAAAA AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar)
UCHIJAAAAAAAAA CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar)
UCHIJAAAAAAAAA ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.4-114.jar)
UCHIJAAAAAAAAA ImmersiveEngineering{0.7.7} [Immersive Engineering](ImmersiveEngineering-0.7.7.jar)
UCHIJAAAAAAAAA arcane_engineering{0.2.7} [Arcane Engineering](arcane_engineering-0.2.7.jar)
UCHIJAAAAAAAAA Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar)
UCHIJAAAAAAAAA AromaBackup{0.1.0.0} [AromaBackup](AromaBackup-1.7.10-0.1.0.0.jar)
UCHIJAAAAAAAAA AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.7.10-0.1.0.0.jar)
UCHIJAAAAAAAAA BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar)
UCHIJAAAAAAAAA ExtrabiomesXL{3.16.4} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.4.jar)
UCHIJAAAAAAAAA BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition](BiblioWoods[ExtraBiomesXL][v1.4].jar)
UCHIJAAAAAAAAA AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar)
UCHIJAAAAAAAAA Botania{r1.8-248} [Botania](Botania r1.8-248.jar)
UCHIJAAAAAAAAA cfm{3.4.8} [§9MrCrayfish's Furniture Mod](cfm-3.4.8-mc1.7.10.jar)
UCHIJAAAAAAAAA TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar)
UCHIJAAAAAAAAA chisel{2.9.5.11} [Chisel](Chisel-2.9.5.11.jar)
UCHIJAAAAAAAAA chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar)
UCHIJAAAAAAAAA craftarcanum{1.0.1} [Craft Arcanum](CraftArcanum-1.0.1.jar)
UCHIJAAAAAAAAA craftguide{1.6.8.1} [CraftGuide](CraftGuide-Mod-1.7.10.zip)
UCHIJAAAAAAAAA craftingpillars{1.6.0} [Crafting Pillars Mod](CraftingPillars-1.7.x-1.6.1.jar)
UCHIJAAAAAAAAA CustomSpawner{3.3.0} [DrZhark's CustomSpawner](CustomMobSpawner 3.3.0.zip)
UCHIJAAAAAAAAA customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d%2821feb16%29.jar)
UCHIJAAAAAAAAA MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip)
UCHIJAAAAAAAAA DummyCore{1.13} [DummyCore](DummyCore1.13.jar)
UCHIJAAAAAAAAA IC2{2.2.821-experimental} [IndustrialCraft 2](Industrial-Craft-2-Mod-Experimental-1.7.10.jar)
UCHIJAAAAAAAAA EMT{2.0.0Alpha4} [Electro-Magic Tools](ElectroMagicTools-1.7.10-2.0.0Alpha-29.jar)
UCHIJAAAAAAAAA ESM{10.0.148} [Epic Siege Mod](EpicSiegeMod-10.0.148.jar)
UCHIJAAAAAAAAA flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar)
UCHIJAAAAAAAAA ForbiddenMagic{1.7.10-0.575} [Forbidden Magic](Forbidden Magic-1.7.10-0.575.jar)
UCHIJAAAAAAAAA gadomancy{1.0.7.2} [Gadomancy](gadomancy-1.7.10-1.0.7.2.jar)
UCHIJAAAAAAAAA GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3](GrimoireOfGaia3-1.7.10-1.2.7.jar)
UCHIJAAAAAAAAA lmmx{10} [LittleMaidMobEnhanced](LittleMaidMobEnhanced-1.7.10-1.4.4.jar)
UCHIJAAAAAAAAA RadixCore{2.1.2} [RadixCore](RadixCore-1.7.10-2.1.2-universal.jar)
UCHIJAAAAAAAAA MCA{1.7.10-5.2.1} [Minecraft Comes Alive](MCA-1.7.10-5.2.1-universal.jar)
UCHIJAAAAAAAAA MoreFurnaces{1.3.9} [More Furnaces](More-Furnaces-Mod-1.7.10.jar)
UCHIJAAAAAAAAA Mystcraft{0.12.3.02} [Mystcraft](mystcraft-1.7.10-0.12.3.02.jar)
UCHIJAAAAAAAAA harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar)
UCHIJAAAAAAAAA Roguelike{1.5.0} [Roguelike Dungeons](roguelike-1.7.10-1.5.0b.jar)
UCHIJAAAAAAAAA benway_knowledge{0.1.5.1} [Thaumaturgical Knowledge](Thaumaturgical Knowledge-0.1.5.2 - 1.7.10.jar)
UCHIJAAAAAAAAA ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar)
UCHIJAAAAAAAAA TU{1.0} [Thaumic Upholstry](Thaumic_Upholstery-1.2_1.7.10.jar)
UCHIJAAAAAAAAA thebetweenlands{1.0.6-alpha} [The Betweenlands](TheBetweenlands-1.0.6-alpha-universal.jar)
UCHIJAAAAAAAAA ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar)
UCHIJAAAAAAAAA worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar)
UCHIJAAAAAAAAA XaeroMinimap{1.4.5.1} [Xaero's Minimap](xaeros_minimap_v1.4.5.1_1.7.10_Forge.jar)
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
CoFHCore: -[1.7.10]3.1.2-325
ThermalFoundation: -[1.7.10]1.2.4-114
ThermalExpansion: -[1.7.10]4.1.2-240
Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 1 / 8; [EntityPlayerMP['Mariku_Junrei'/111353, l='New World', x=-169.23, y=93.00, z=297.63]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
OptiFine Version: OptiFine_1.7.10_HD_U_D6
Render Distance Chunks: 8
Mipmaps: 3
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
OpenGlVersion: 3.1.0 - Build 9.17.10.4229
OpenGlRenderer: Intel(R) HD Graphics 3000
OpenGlVendor: Intel
CpuCount: 4

**Comment by Goujer** [comment]
This appears to be caused by Mine and Blade trying to find out what a maid has in its second hand slot (a Mine and Blade feature). Mine and Blade casts the maids inventory to its InventoryPlayerBattle to use this second hand slot method but crashes since maids extend the InventoryPlayer and are not an instance of InventoryPlayerBattle. A check on the Mine and Blade side to see if the entity inventory is a InventoryPlayer and not InventoryPlayerBattle would be the simplest way to solve this bug.

**Comment by Goujer** [comment]
A check has been placed into the Battlegear2's AbsractMBArrow that solves the issue.
It is up to BattleGear2's Developer to implement into a release.
